ALTER TYPE "CampaignStatus" ADD VALUE IF NOT EXISTS 'PAUSED';

ALTER TYPE "ToolExecutionStatus" ADD VALUE IF NOT EXISTS 'PENDING_CONFIRMATION';
ALTER TYPE "ToolExecutionStatus" ADD VALUE IF NOT EXISTS 'CANCELED';
